- hosts: localhost
  connection: local
  tasks:
    - name: Load change variables
      include_vars:
        file: "{{ playbook_dir }}/change.yml"
        name: change_vars
    - name: Load list of hosts
      include_vars:
        file: "{{ playbook_dir }}/hosts.yml"
        name: hosts
    - name: Validate that specified target hosts in change.yml exist in hosts
      assert:
        that:
          - "'{{ item }}' in hosts"
      loop: "{{ change_vars.target }}"

    - name: Add specified target hosts in a switches inventory group
      add_host:
        name: "{{ item }}"
        groups: switches
        ansible_host: "{{ hosts[item]['hostname'] }}"
        ansible_network_os: "{{ hosts[item]['network_os'] }}"
        ansible_user: "{{ hosts[item]['user'] }}"
        ansible_password: "{{ hosts[item]['password'] }}"
      loop: "{{ change_vars.target }}"
  
- name: Configure vlans
  hosts: switches
  gather_facts: false
  connection: network_cli
  roles:
  - role-vlan-generator
