---
- hosts: localhost
  connection: local
  tasks:
    - include_vars:
        file: "{{ playbook_dir }}/change.yml"
        name: change_vars
    - include_vars:
        file: "{{ playbook_dir }}/hosts.yml"
        name: hosts
    - assert:
        that:
          - "'{{ item }}' in hosts"
      loop: "{{ change_vars.target }}"

    - add_host:
        name: "{{ item }}"
        groups: switches
        ansible_host: "{{ hosts[item]['hostname'] }}"
        ansible_network_os: "{{ hosts[item]['network_os'] }}"
        ansible_user: "{{ hosts[item]['user'] }}"
        ansible_password: "{{ hosts[item]['password'] }}"
      loop: "{{ change_vars.target }}"

- hosts: switches
  gather_facts: false
  connection: network_cli
  tasks:
    - eos_command:
        commands:
          - show version
